#!/bin/bash -l
#$ -S /bin/bash
#$ -l h_rt=3:00:00
#$ -l mem=1G
#$ -N BP_8ribbon_2_layer_geomopt_AA
#$ -pe qlc 64
#$ -cwd
#$ -o q.output
#$ -e q.error

ulimit -s unlimited
ulimit -m unlimited

gerun ${HOME}/bin/vasp_std > vasp_out
